---
- name: Server setup using ansible
  hosts: all
  become: true
  tasks:
    - name: Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: Install 
      ansible.builtin.apt:
        pkg:
          - postgresql 
          - postgresql-contrib 
          - tomcat9
